
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports: ["5432:5432"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
  airflow:
    image: apache/airflow:2.9.2
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__WEBSERVER__BASE_URL: http://localhost:8080
    command: webserver
    depends_on: [postgres, redis]
    ports: ["8080:8080"]
    volumes:
      - ./../airflow/dags:/opt/airflow/dags
